In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
c = np.array([7,8,9], dtype='int16')
c

array([7, 8, 9], dtype=int16)

In [4]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
# Some core attributes
print("dimension of array b is",b.ndim) # number of dimensions
print("shape of b is", b.shape) # Tuple of size per dimension
print("size of array b is", b.size) # Total number of elements
print("dtype", b.dtype) # Datatype of the elements
print("itemsize of b is", b.itemsize , "bytes") # Size per element
print("nbytes", b.nbytes, "bytes") # Total memory (is same as b.size * b.itemsize)
 


dimension of array b is 2
shape of b is (2, 3)
size of array b is 6
dtype float64
itemsize of b is 8 bytes
nbytes 48 bytes


In [6]:
print("itemsize of a", a.itemsize)
print("itemsize of c", c.itemsize)

itemsize of a 8
itemsize of c 2


In [7]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
x

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [8]:
# To get a specific element [x,y]
print(x[1,4])
print(x[1,-3])

12
12


In [9]:
print(x[0, :]) # To get a specific row
print(x[:,0]) # To get a specific column


[1 2 3 4 5 6 7]
[1 8]


In [10]:
# To get [ row, startindex: endindex: stepsize]
print(x[0,1:6:2])
print(x[0,1:-1:2])

[2 4 6]
[2 4 6]


In [11]:
x[1,5] = 15
print(x)

x[:,2] = [1,2]
print(x)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 15 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 15 14]]


In [12]:
# In 3D
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
y


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
# To get a specific element (Work outside in)
print(y[0,1,1])
print(y[:,1,:]) # To get elements in index 1 of both

4
[[3 4]
 [7 8]]


In [14]:
# To replace
y[:,1,:] = [[9,9],[8,8]]
y

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing different types of arrays

In [15]:
# some pre built arrays - can be done on any dimension
zero = np.zeros((2,3)) 
one = np.ones((2,3)) # we can write np.ones((2,3), dtype = 'int16')
full = np.full((2,2),fill_value=2) # can be written in short as np.full((2,2),2)
print(zero)
print(one)
print(full)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]]


In [16]:
# Any other number (full_like)
print(np.full_like(x.shape, 4))
# Identity Matrix
print(np.eye(3)) # or np.identity(3)

[4 4]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
ar = np.arange(0,10, step=3)
ar

array([0, 3, 6, 9])

In [18]:
# Generate equally‑spaced samples between given start and stop value.Also includes both endpoints by default.
ls = np.linspace(0,1,num=3) 
ls

array([0. , 0.5, 1. ])

In [19]:
# For random decimal numbers
print(np.random.rand(4,2)) # its not np.random.rand((4,2))
print(np.random.randn(4,2)) # For random normal numbers

[[0.74643627 0.07355041]
 [0.71743396 0.06551138]
 [0.24510659 0.88870087]
 [0.43839268 0.29231553]]
[[-1.56317171 -0.66246249]
 [ 0.29025415  0.51436855]
 [ 0.94130471 -0.0541495 ]
 [-0.69902462  1.00647387]]


In [20]:
print("x",np.random.random_sample(x.shape)) # with shape as well
print("a",np.random.random_sample(a.shape)) # with shape as well

x [[0.28564243 0.8340279  0.88231948 0.29391389 0.85477763 0.83463271
  0.89209462]
 [0.23907244 0.71315388 0.79826452 0.74556432 0.63313316 0.58415887
  0.1044492 ]]
a [0.9353567  0.4866551  0.55080939]


In [21]:
# For Random Integer Values
np.random.randint(-2,4,size = (2,2)) # between -2 and 4 exclusive

array([[-2,  2],
       [ 3, -2]], dtype=int32)

In [22]:
# To repeat elements in an array
arr1D = np.array([1,2,3])
r1D = np.repeat(arr1D,3)
print(r1D)

arr2D = np.array([[1,2,3]])
r2D_0 = np.repeat(arr2D,3,axis=0)
r2D_1 = np.repeat(arr2D,3,axis=1)
print(r2D_0)
print(r2D_1)


[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [23]:
# Trying a 5 * 5 Matrix
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z # same as output[1:-1,1:-1] 
print(output)        # 1,-1 -> starts at index 1 and goes upto last row # 1,4 takes columns 1,2,3

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Copying Arrays

In [24]:
# if .copy() is not used any changes made in f will be refleced in g as well
g = np.array([1,2,3])
f = g.copy()
f[0] = 100
print(f)
print(g)

[100   2   3]
[1 2 3]


Maths

In [25]:
h = np.array([1,2,3,4])
i = h + 2 # can do - , * , /
print(h)
print(i)
h+=4
print(h)
print(h**2)
print(np.sin(h))
# can perfrom the above functions between two arrays as well

[1 2 3 4]
[3 4 5 6]
[5 6 7 8]
[25 36 49 64]
[-0.95892427 -0.2794155   0.6569866   0.98935825]


In [26]:
# Element‑wise
A = np.array([1,2,3])
B = np.array([4,5,6])
print(np.add(A, B), A + B)

# Scalar‑array
print(np.exp(A), np.sqrt(B))

# Reductions
data = np.random.randn(1000)
print(data.sum(), data.mean(), data.min(), data.max())
print(data.cumsum()[:5])  # running total

[5 7 9] [5 7 9]
[ 2.71828183  7.3890561  20.08553692] [2.         2.23606798 2.44948974]
49.16409052297998 0.04916409052297998 -3.3884354860838126 3.238596967412902
[1.92999941 1.16875111 2.04722365 3.80139408 5.2488159 ]


In [27]:
u = np.ones((2,3))
print(u)

v = np.full((3,2),2)
print(v)

np.matmul(u,v)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [28]:
# To find determinant
w = np.identity(3)
np.linalg.det(w)


np.float64(1.0)

In [29]:
tr    = np.trace(w)                 #  Trace entries
U, S, Vt = np.linalg.svd(w)         # Singular Value Decomposition
eigvals, eigvecs = np.linalg.eig(w) # Eigenvalues & Eigenvectors
normF = np.linalg.norm(w)           # Frobenius Norm
invA  = np.linalg.inv(w)            # Inverse

In [30]:
# Data type & Casting
float_arr = np.array([1.1, 2.2, 3.3], dtype=np.float32)
int_arr   = float_arr.astype(np.int64)  # explicit cast

In [31]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
print(np.max(stats))
print(np.min(stats, axis = 0))
print(np.min(stats, axis = 1))
print(np.sum(stats, axis = 1))
print(np.sum(stats, axis = 0))

6
[1 2 3]
[1 4]
[ 6 15]
[5 7 9]


Reorganizing Arrays     

In [33]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# Vertically stacking vectors/ matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]))

# Horizontal Stack

print(np.hstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


Loading Data From file  

In [35]:
# 'file.txt' should contain rows of numbers separated by commas.
# genfromtxt returns a float array by default, using NaN for missing values.
data = np.genfromtxt(r"C:\Users\MSP\Downloads\file.txt", delimiter=',')
data



array([[102., 179.,  92.,  14., 106., 145., 132.,  19., 164.,  25., 106.,
        123., 136., 101.,  68., 125., 107.,  47.],
       [308., 343., 491., 413., 385., 505., 325., 533., 501., 207., 315.,
        377., 304., 261., 436., 231., 556., 657.]])

In [36]:
# astype('int32') returns a new array with dtype int32.
# Note: this does NOT modify `data` in place; you need to assign it if you want to keep it.

data.astype('int32')

array([[102, 179,  92,  14, 106, 145, 132,  19, 164,  25, 106, 123, 136,
        101,  68, 125, 107,  47],
       [308, 343, 491, 413, 385, 505, 325, 533, 501, 207, 315, 377, 304,
        261, 436, 231, 556, 657]], dtype=int32)

Boolean Masking and Advanced indexing

In [37]:
data > 50

array([[ True,  True,  True, False,  True,  True,  True, False,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [38]:
data[data > 50]

array([102., 179.,  92., 106., 145., 132., 164., 106., 123., 136., 101.,
        68., 125., 107., 308., 343., 491., 413., 385., 505., 325., 533.,
       501., 207., 315., 377., 304., 261., 436., 231., 556., 657.])

In [39]:
# we can index with a list in numpy
ap = np.array([1,2,3,4,5,6,7,8,9])
ap[[1,2,8]]


array([2, 3, 9])

In [40]:
np.any(data > 50, axis = 0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [41]:
np.all(data > 50, axis = 0)

array([ True,  True,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False])

In [42]:
np.any(data > 50, axis = 1)

array([ True,  True])

In [43]:
((data>50)&(data<100))
# ~ is not -> (~(data>50)&(data<100)) gives the opposite of the above values

array([[False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [44]:
M = np.arange(12).reshape(3, 4)
print(M)

# Boolean indexing
mask = M % 2 == 0
evens = M[mask]
print(evens)

# Fancy indexing
idx = [0, 2]             # pick rows 0 & 2
sel = M[idx, [1, 3]]     # elements (0,1) and (2,3)
print(sel)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  2  4  6  8 10]
[ 1 11]


In [45]:
V = np.arange(6)             
W = V.reshape((2,3))         
flat = W.ravel()             # flatten w into 1D shape
copy = W.copy()              # new array , own data
print(V)
print(W)
print(flat)
print(copy)


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [46]:
mat = np.ones((4,3))
vec = np.array([1,2,3])    
print("mat",mat)
print("vec",vec)
print("sum",mat+vec)                   # vec broadcast to each of 4 rows


mat [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
vec [1 2 3]
sum [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


Vectorized ufuncs in NumPy are “universal functions” that operate element‑wise on arrays entirely in C, so you get big speedups by avoiding Python‑level loops.
C loops are orders of magnitude faster than Python for‑loops.

In [47]:
x = np.random.rand(1_000_000)

# Python loop version
def sq_loop(x):
    out = np.empty_like(x)
    for i in range(x.size):
        out[i] = x[i]**2
    return out

# Vectorized (ufunc) version
def sq_vec(x):
    return x**2


In [48]:
%timeit sq_loop(x)   
%timeit sq_vec(x)    

270 ms ± 6.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.09 ms ± 51.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


The .cumsum() method computes the cumulative sum of an array’s elements along a given axis.

In [49]:
data = np.array([1,20,3,40])
cumilative = data.cumsum()
cumilative

array([ 1, 21, 24, 64])