In [1]:
import numpy as np

In [2]:
# Create a 5×5 ndarray of 0–24. Extract its border (first/last rows & cols).
arr = np.arange(25).reshape(5,5)
print(arr)
toprow = arr[0,:]
bottomrow = arr[-1,:]
firstcol = arr[1:-1,0]
lastcol = arr[1:-1,-1]
print(toprow)
print(bottomrow)
print(firstcol)
print(lastcol)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4]
[20 21 22 23 24]
[ 5 10 15]
[ 9 14 19]


In [3]:
# For a 1D randn(1000), compute mean & variance without np.mean/var; verify results.
random = np.random.rand(1000)
np_mean = np.mean(random)
np_var = np.var(random)
mean = random.sum() / random.size
variance = ((random - mean)**2).sum() / random.size
print(np_mean)
print(np_var)
print(mean)
print(variance)

0.5141434826483114
0.08595552783994793
0.5141434826483114
0.08595552783994793


In [4]:
# Compute pairwise Euclidean distances using vectorized broadcasting. 
import numpy as np

def pairwise_euclidean(X):
   
    diff = X[:, None, :] - X[None, :, :]
    D = np.sqrt((diff ** 2).sum(axis=-1))
    return D

X = np.array([[0,0],
              [1,0],
              [0,2]])
# distances between (0,0),(1,0),(0,2)
D = pairwise_euclidean(X)
print(D)



[[0.         1.         2.        ]
 [1.         0.         2.23606798]
 [2.         2.23606798 0.        ]]


In [5]:
# Center each row of a 3×3 array by subtracting its mean.

A = np.array([[ 1,  2,  3], [10, 20, 30], [ 5,  7,  9]])
row_means = A.mean(axis=1, keepdims=True)  # keepdims=True makes the result shape (3,1) instead of (3,).
A_centered = A - row_means

print("Original:\n", A)
print("\nRow means:\n", row_means)
print("\nCentered:\n", A_centered)


Original:
 [[ 1  2  3]
 [10 20 30]
 [ 5  7  9]]

Row means:
 [[ 2.]
 [20.]
 [ 7.]]

Centered:
 [[ -1.   0.   1.]
 [-10.   0.  10.]
 [ -2.   0.   2.]]


In [6]:
# To show modifying a slice can or cannot affect the original array.

# 1. Create an array and take a slice (which is a VIEW, not a copy)
a = np.arange(6).reshape(2, 3)
print("Original a:\n", a)

view = a[0, :]        # slice of the first row
view[1] = 99          # modify the slice
print("\nAfter modifying view[1] = 99:")
print("a:\n", a)


# 2. Take a copy explicitly
b = np.arange(6).reshape(2, 3)
copy = b[0, :].copy()  # this is a deep copy
copy[1] = -1            # modify the copy
print("\nAfter modifying copy[1] = -1:")
print("b:\n", b)



Original a:
 [[0 1 2]
 [3 4 5]]

After modifying view[1] = 99:
a:
 [[ 0 99  2]
 [ 3  4  5]]

After modifying copy[1] = -1:
b:
 [[0 1 2]
 [3 4 5]]
